In [2]:
from IPython.core.display_functions import display
# import module
import pandas as pd

# Read excel file
# and store into a DataFrame
df1 = pd.read_excel('bihar_stud_result.xlsx')
df2 = pd.read_excel('up_stud_result.xlsx')

display(df1)
display(df2)
# concat both DataFrame into a single DataFrame
df = pd.concat([df1, df2])
df.reset_index(inplace=True,drop=True)
display(df)
# Export Dataframe into Excel file
df.to_excel('final_stud_result.xlsx', index=False)

   Roll No      Subject  Marks
0      101  Mathematics     86
1      102      English     45
2      103        Hindi     75

   Roll No  Subject  Marks
0      126  Science     70
1      127  English     40
2      128     Urdu     80

   Roll No      Subject  Marks
0      101  Mathematics     86
1      102      English     45
2      103        Hindi     75
3      126      Science     70
4      127      English     40
5      128         Urdu     80