In [24]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {'a': range(1, 11), 'b': ['one', 'two', 'three', 'four', 'four', 'four', 'five', 'five', 'six', 'seven'],
     'c': np.random.random(10), 'd': np.random.random(10) * 10})

display(df)
#display(df['c'].sum())
#display(df[['c','d']].sum())
#display(df['d'].min())
#display(df['d'].mean())
#display(df.loc[:,'d'])
#display(df.loc[0])
#display(df.loc[0,'d'])
#display(df.loc[df['d']>5])
#display(df.loc[df['b']=='five'])

#display(df.iloc[:5,:2])
#bottom 5 rows and last 2 columns
#display(df.iloc[-5:,-2:])
#display(df.groupby(['b']).mean())
df['e'] = [1, 1, 1, 1, 0, 0, 1, 0, 1, 1]
display(df)
display(df.groupby(['b', 'e']).mean())
display(df.groupby(['e']).mean())

    a      b         c         d
0   1    one  0.571744  6.346290
1   2    two  0.789148  6.478174
2   3  three  0.277925  0.589466
3   4   four  0.289993  5.195427
4   5   four  0.377521  7.029675
5   6   four  0.648304  0.395623
6   7   five  0.124837  9.713544
7   8   five  0.740585  7.185280
8   9    six  0.216317  9.398903
9  10  seven  0.251121  3.240684

    a      b         c         d  e
0   1    one  0.571744  6.346290  1
1   2    two  0.789148  6.478174  1
2   3  three  0.277925  0.589466  1
3   4   four  0.289993  5.195427  1
4   5   four  0.377521  7.029675  0
5   6   four  0.648304  0.395623  0
6   7   five  0.124837  9.713544  1
7   8   five  0.740585  7.185280  0
8   9    six  0.216317  9.398903  1
9  10  seven  0.251121  3.240684  1

            a         c         d
b     e
five  0   8.0  0.740585  7.185280
      1   7.0  0.124837  9.713544
four  0   5.5  0.512913  3.712649
      1   4.0  0.289993  5.195427
one   1   1.0  0.571744  6.346290
seven 1  10.0  0.251121  3.240684
six   1   9.0  0.216317  9.398903
three 1   3.0  0.277925  0.589466
two   1   2.0  0.789148  6.478174

          a         c         d
e
0  6.333333  0.588803  4.870193
1  5.142857  0.360155  5.851784