In [5]:
import pandas as pd

df1 = pd.DataFrame({'id': ['A01', 'A02', 'A03', 'A04'],
					'Name': ['ABC', 'PQR', 'DEF', 'GHI']})
display(df1)
df2 = pd.DataFrame({'City': ['MUMBAI', 'PUNE', 'MUMBAI', 'DELHI'],
					'Age': ['12', '13', '14', '12']})
display(df2)
# the default behaviour is join='outer'
# inner join

result = pd.concat([df1, df2], axis=1, join='inner')
display(result)

    id Name
0  A01  ABC
1  A02  PQR
2  A03  DEF
3  A04  GHI

     City Age
0  MUMBAI  12
1    PUNE  13
2  MUMBAI  14
3   DELHI  12

    id Name    City Age
0  A01  ABC  MUMBAI  12
1  A02  PQR    PUNE  13
2  A03  DEF  MUMBAI  14
3  A04  GHI   DELHI  12