In [1]:
from IPython.core.display_functions import display
import pandas as pd

# Creating dataframe
df1 = pd.DataFrame({'Name': ['rumul', 'rahul',
                             'ravi', 'imran'],
                    'Marks': [5, 20, 8, 12]})

df2 = pd.DataFrame({'Name': ['rumul', 'rahul',
                             'purvi', 'ravi',
                             'imran'],
                    'Marks': [18, 19, 13, 11, 15]})

display(df1)
display(df2)

# replace values of one DataFrame with
# the value of another DataFrame
df1['Marks'] = df2[df2['Name'].isin(df1['Name'])]['Marks'].values

display(df1)

    Name  Marks
0  rumul      5
1  rahul     20
2   ravi      8
3  imran     12

    Name  Marks
0  rumul     18
1  rahul     19
2  purvi     13
3   ravi     11
4  imran     15

    Name  Marks
0  rumul     18
1  rahul     19
2   ravi     11
3  imran     15