In [18]:
from IPython.core.display_functions import display
import pandas as pd

# initialise data of lists.
colors = {'first_set': ['99', '88', '77', '66',
                        '55', '44', '33', '22'],
          'second_set': ['1', '2', '3', '4', '5',
                         '6', '7', '8']
          }

color = {'first_set': ['a', 'b', 'c', 'd', 'e',
                       'f', 'g', 'h'],
         'second_set': ['VI', 'IN', 'BL', 'GR',
                        'YE', 'OR', 'RE', 'WI']
         }
# Calling DataFrame constructor on list
df1 = pd.DataFrame(colors, columns=['first_set', 'second_set'])
df2 = pd.DataFrame(color, columns=['first_set', 'second_set'])
# Display the Output
display(df1)
display(df1)

# selecting old value
a = df2['first_set'][4]
# selecting new value
b = df1['first_set'][1]
# replace values of one DataFrame
# with the value of another DataFrame
df2 = df2.replace(a, b)
# Display the Output
display(df2)

# Display the Output
display(df1)
display(df2)
# Selecting old value
a = df1['first_set'][4]
# Selecting new value
b = df2['first_set'][1]
# replace values of one DataFrame with
# the value of another DataFrame
df1 = df1.replace(a, b)
# Display the Output
display(df1)

#selected value
a = df1['first_set'][4]
b = df2['second_set'][1]
# replace values of one DataFrame with
# the value of another DataFrame
df1 = df1.replace(a, 'Hello')
# replace values of one DataFrame with
# the value of another DataFrame
df2 = df2.replace(b, 'Geeks')
display(df1)
display(df2)

# replace column of one DataFrame with
# the column of another DataFrame
#df1['second_set'] = df2.replace(df1['first_set'], df1['second_set'])
#display(df1)

# replacing value of DataFrame
df1.first_set[df1.first_set == '66'] = 'DF1'
df2.first_set[df2.first_set == 'g'] = 'DF2'
# display updated table
display(df1)
display(df2)

  first_set second_set
0        99          1
1        88          2
2        77          3
3        66          4
4        55          5
5        44          6
6        33          7
7        22          8

  first_set second_set
0        99          1
1        88          2
2        77          3
3        66          4
4        55          5
5        44          6
6        33          7
7        22          8

ValueError: Columns must be same length as key