In [31]:
# Import pandas package
import pandas as pd

# Define a dictionary containing employee data
data = {'Income': [150000, 13000, 11000, 11000],
		'Expenses': [10000, 11000, 7000, 50000],
		'Profit': [5000, 2000, 4000, 6000]
		}


# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print('1'*30)
# Observe the result
display(df)

# # Reverse rows using iloc() Function
# Data_reverse_row_1 = df.iloc[::-1]
# # Observe the result
# Data_reverse_row_1

# # Reverse rows using iloc() Function
# Data_reverse_row_2 = df.loc[::-1]
# # Observe the result
# Data_reverse_row_2

# # reversing a DataFrame
# # retrieving row by reindex method
# dataframe.reindex(index=df.index[::-1])
print('2'*30)
# Reverse slicing columns in data frame
df1=df[::-1]
display(df1)

print('3'*30)
df1.reset_index(inplace=True,drop=True)
display(df1)

111111111111111111111111111111

   Income  Expenses  Profit
0  150000     10000    5000
1   13000     11000    2000
2   11000      7000    4000
3   11000     50000    6000

222222222222222222222222222222

   Income  Expenses  Profit
3   11000     50000    6000
2   11000      7000    4000
1   13000     11000    2000
0  150000     10000    5000

333333333333333333333333333333

   Income  Expenses  Profit
0   11000     50000    6000
1   11000      7000    4000
2   13000     11000    2000
3  150000     10000    5000