In [35]:
import pandas as pd

student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

# create DataFrame from dict
student_df = pd.DataFrame(student_dict)
display(student_df)
#display(student_df.loc[student_df['Name']=='Nat'])

#set index using column
student_df = student_df.set_index('Name')
display(student_df)
student_df.reset_index(inplace=True)
display(student_df)

#display(student_df.loc['Nat'].values.flatten().tolist())
#display(student_df.loc[['Nat']])

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

       Age  Marks
Name
Joe     20  85.10
Nat     21  77.80
Harry   19  91.54

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54