In [12]:
from IPython.core.display_functions import display
import pandas as pd

# Single level columns
df_single_level_cols = pd.DataFrame([[74, 80], [72, 85]],
                                    index=['Deepa', 'Balram'],
                                    columns=['Maths', 'Computer'])
display(df_single_level_cols)

# Single level with stack()
display(df_single_level_cols.stack())

# Simple Multi-level columns
multicol1 = pd.MultiIndex.from_tuples([('Science', 'Physics'),
                                       ('Science', 'Chemistry')])

df_multi_level_cols1 = pd.DataFrame([[80, 64], [76, 70]],
                                    index=['Deepa', 'Balram'],
                                    columns=multicol1)

display(df_multi_level_cols1)
display(df_multi_level_cols1.stack())

# Multi-level with missing values
multicol2 = pd.MultiIndex.from_tuples([('English', 'Literature'),
                                       ('Hindi', 'Language')])

df_multi_level_cols2 = pd.DataFrame([[80, 75], [80, 85]],
                                    index=['Deepa', 'Balram'],
                                    columns=multicol2)
display(df_multi_level_cols2)
# Multi-level missing values as NaN
display(df_multi_level_cols2.stack())

# Prescribing the level(s) to be stacked
display(df_multi_level_cols2.stack(0))

# The first parameter controls which level
# or levels are stacked
display(df_multi_level_cols2.stack([0, 1]))

# Dropping missing values
df_multi_level_cols3 = pd.DataFrame([[None, 80], [77, 82]],
                                    index=['Deepa', 'Balram'],
                                    columns=multicol2)
display(df_multi_level_cols3)

# contains the row with all NaN values since,
# dropna=False
df_multi_level_cols3.stack(dropna=False)
display(df_multi_level_cols3)

# Drops the row with completely NaN values
df_multi_level_cols3.stack(dropna=True)
display(df_multi_level_cols3)

        Maths  Computer
Deepa      74        80
Balram     72        85

Deepa   Maths       74
        Computer    80
Balram  Maths       72
        Computer    85
dtype: int64

       Science
       Physics Chemistry
Deepa       80        64
Balram      76        70

                  Science
Deepa  Chemistry       64
       Physics         80
Balram Chemistry       70
       Physics         76

          English    Hindi
       Literature Language
Deepa          80       75
Balram         80       85

                   English  Hindi
Deepa  Language        NaN   75.0
       Literature     80.0    NaN
Balram Language        NaN   85.0
       Literature     80.0    NaN

                Language  Literature
Deepa  English       NaN        80.0
       Hindi        75.0         NaN
Balram English       NaN        80.0
       Hindi        85.0         NaN

Deepa   English  Literature    80.0
        Hindi    Language      75.0
Balram  English  Literature    80.0
        Hindi    Language      85.0
dtype: float64

          English    Hindi
       Literature Language
Deepa         NaN       80
Balram       77.0       82

          English    Hindi
       Literature Language
Deepa         NaN       80
Balram       77.0       82

          English    Hindi
       Literature Language
Deepa         NaN       80
Balram       77.0       82